describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:4200')
    cy.get('.logo').click()
    cy.get('#pn_id_1_1 > .p-menubar-item-content > .p-ripple > .p-menubar-item-label').click()
    cy.get('#email1').type("miau@gmail.com")
    cy.get('#username1').type("miau1")
    cy.get('#password1').type("123")
    cy.get('#confirmPassword1').type("123")
    cy.get('.p-checkbox-input').click()
    cy.get(':nth-child(2) > .p-ripple').click()

    cy.get('.text-center > .no-underline').click()
    cy.get('#email1').type("miau@gmail.com")
    cy.get('#password1').type("123")
    cy.get('.p-checkbox-input').click()
    cy.get('form.ng-dirty > .p-ripple').click()

    //cy.get('#pn_id_1_2 > .p-menubar-item-content > .p-ripple > .p-menubar-item-label').click()
    //cy.get('.add-question-button > .p-ripple').click()
    //cy.get('#title').type("Profesori UTCN")
    //cy.get('#content').type("Care e cel mai bun profesor dsin cadru UTCN-ului?")
    //cy.get('.p-autocomplete > .p-inputtext').type("Cadre didactice UT Cluj Napoca")
    //cy.get('.create-tag-prompt > .p-button').click()
    //cy.get('#newTagDescription').type("Universitatea Tehnica Cluj Napoca")
    //cy.get('[label="Confirmă Creare"]').click()
    //cy.get('.p-mt-4').click()

    cy.get('.logo').click()
    cy.get('.avatar > img').click()
    cy.get(':nth-child(1) > .flex > span').click()
    cy.get('.avatar > img').click()
    cy.get(':nth-child(2) > .flex > span').click()

    cy.get('#pn_id_1_1 > .p-menubar-item-content > .p-ripple > .p-menubar-item-label').click()
    cy.get('#email1').type("ham@gmail.com")
    cy.get('#username1').type("Lucas")
    cy.get('#password1').type("12233")
    cy.get('#confirmPassword1').type("12233")
    cy.get('.p-checkbox-input').click()
    cy.get(':nth-child(2) > .p-ripple').click()
    cy.get('.text-center > .no-underline').click()
    cy.get('#email1').type("ham@gmail.com")
    cy.get('#password1').type("12233")
    cy.get('.p-checkbox-input').click()
    cy.get('form.ng-dirty > .p-ripple').click()

    cy.get('#pn_id_1_2 > .p-menubar-item-content > .p-ripple > .p-menubar-item-label').click()
    cy.get(':nth-child(2) > .vote-buttons > .vote-down-button').click()
    cy.get(':nth-child(2) > .vote-buttons > .vote-up-button').click()
    cy.get(':nth-child(2) > .add-answer-button > .p-ripple').click()
    cy.get('#content').type("Cel mai bun profesor e Bogdan Nicusor Bindea")
    cy.get('form.ng-dirty > .flex > .p-ripple').click()

    cy.get('.logo').click()
    cy.get('.p-inputtext').type("cel mai bun")
    cy.get('.navbar-end > .p-ripple').click()
    cy.get(':nth-child(2) > .flex > span').click()

    //cy.get('.logo').click()
    //cy.get('.avatar > img').click()

  })
})
